.gitignore, docker/base/Dockerfile, docker/cuda-9.2/Dockerfile, docker/r/Dockerfile
* adds `gxx_linux-64` via `apt-get` to resolve the failing build (see #14)
* installs `musl-dev` to resolve the psutil failure on `renku update` (see #14)
* install renku via `pipx` instead of conda
* also, replace deprecated `MAINTAINER` with `LABEL maintainer=< >` in Dockerfiles
You can pull `rrrrrok/base:latest` to check the image.
=> Update base image to fix build problems and psutil dependency

docker/base/Dockerfile, docker/base/lifecycle/pre-stop.sh
This is a jupyter part of the issue raised for `renku-notebooks` (https://github.com/SwissDataScienceCenter/renku-notebooks/issues/126)
It introduces `pre-stop` and `post-start` scripts to be executed by Kubernetes when jupyter container got created and before killing.
=> pre-stop and post-start pod lifecycle scripts

docker/base/Dockerfile
`renku log --format dot` needs graphviz for generating the png file. This PR installs graphviz by default into the base image.
=> feat: add graphviz to base image

docker/base/Dockerfile, docker/base/requirements.txt
The renku-jupyterlab-ts extension does not work yet with
JupyterLab>=1.0.0 -- it requires significant updates in
any case, so it should be removed until these issues
are resolved.
closes #39
closes #40
=> fix: remove jupyterlab extension

Makefile, docker/r/Dockerfile, docker/r/entrypoint.sh
Use the [rocker-versioned](https://github.com/rocker-org/rocker-versioned) rstudio image as the base of our image.
=> build(r): use rocker as a base image for R

.travis.yml
To use `0.7.1`  instead of `0.7.0`
=> build: bump Renku version matrix

.travis.yml, docker/r/Dockerfile, docker/r/entrypoint.sh
Updated travis matrix to include bug fixes on renku-python `0.7.2`
Images not yet tested, will wait on travis to build them first.
Sorry for the merge author, I had some problems with configuring the merging tool which ended up in undoing my git user config. When I merge I will squash so that it disappears.
Addresses: [Prep new release](https://github.com/SwissDataScienceCenter/renku/issues/693)
=> Updated renku version matrix

Makefile, docker/cuda-10.0-tensorflow-1.14/Dockerfile
This PR provides a Renku image for Cuda 10.0 with Tensorflow 1.14
To test:
1. Go to https://limited.renku.ch/projects/51/launchNotebook 
2. Launch a notebook from the latest commit with GPUs and 8GBs of memory
3. From the notebook open a console and execute `python test-tensorflow-gpu.py`
Expected result: the program runs without errors and that at least one GPU device is listed in the logs (similar to https://limited.renku.ch/gitlab/pameladelgado/test2/blob/master/logs-gpu-test/test-log-2gpus.txt)
Fixes partially #19 . Tensorboard comes with the image, but to be able to access it we need to do some port forwarding before running the notebook (https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks)
Update: closes #19
=> image: Cuda 10.0 Tensorflow 1.14

.travis.yml
After adding 
```
branches:
only:
- master
```
travis is not accepting requests of tags for deployment.
The current configuration is equivalent to https://github.com/SwissDataScienceCenter/renku-graph/blob/master/.travis.yml which works.
=> Updated tags travis deploy

docker/base/Dockerfile, docker/base/entrypoint.sh
This PR adds an entrypoint to the base image that copies the contents of the files found in the user's `renku-env` repository in the gitlab instance. It takes the oauth token from the environment and uses it to clone the private `renku-env` repo. If the repo isn't there it fails silently. The contents of all the files in the `renku-env` repository are _appended_ to the corresponding files in `$HOME`.
This requires the user to set up a private `renku-env` repository and it should be documented in the main docs. 
To test, you may either launch an environment from https://renkulab.io/projects/1464/ or use the image `rrrrrok/singleuser:entrypoint` in your own project. 
closes #64
=> feat: inject environment setup into session

docker/base/Dockerfile, docker/base/powerline.bashrc, docker/base/powerline.config, docker/r-bioconductor_3_10/Dockerfile, docker/r-bioconductor_3_10/powerline.bashrc, docker/r-bioconductor_3_10/powerline.config, docker/r/Dockerfile, docker/r/powerline.bashrc, docker/r/powerline.config
Prettifies the terminal shell with powerline. 
screenshot: 
closes #31
=> build: use powerline for terminal prompt

docker/py3.7/Dockerfile, docker/py3.7/requirements.txt
closes #33 
Adds https://github.com/jtpio/jupyterlab-system-monitor which uses https://github.com/yuvipanda/nbresuse.
I think we should add some configs in `~/.jupyter/jupyter_notebook_config.py` like the example before merging:
```
c = get_config()
c.NotebookApp.ResourceUseDisplay.mem_limit = <size_in_GB> *1024*1024*1024
c.NotebookApp.ResourceUseDisplay.track_cpu_percent = True
c.NotebookApp.ResourceUseDisplay.cpu_limit = <number_of_cpus>
```
=> Add nbresuse for resource display in notebooks

.github/workflows/build_and_push_to_docker.yml, docker/r/Dockerfile
=> fix: pin RStudio version

README.md, docker/py/entrypoint.sh, docker/r/Dockerfile, docker/r/post-init.sh
=> fix: global git credentials and some other stuff

docker/py/Dockerfile, docker/r/Dockerfile
Fixes the problem where the jupyterlab git extension environment did not have `~/.local/bin` in the `PATH`
=> fix: ensure local/bin is in PATH

Makefile, docker/py/Dockerfile, docker/py/requirements.txt, scripts/install-vscode.sh
Adds VSCode using [code-server](https://github.com/cdr/code-server) and [jupyter-vscode-proxy](https://github.com/betatim/vscode-binder).
For testing, you can ~~use this image: `renku/renkulab-py:3.7-c43683d`~~ add these lines to your `Dockerfile`:
```
USER root
RUN curl -s https://raw.githubusercontent.com/SwissDataScienceCenter/renkulab-docker/c50af197ccd7b727b9baa0aebf60602c669ab546/scripts/install-vscode.sh | bash
USER ${NB_USER}
```
closes #83
=> feat: add vscode to base image

scripts/install-vscode.sh
avoid jupyter rebuilds on session launch and bump vscode version
you can test it here: https://dev.renku.ch/projects/rokroskar/test-vscode/environments/new (just select `/lab` before launching)
=> chore: do the jupyter build at the end of vscode script

scripts/install-vscode.sh
There are problems with newer versions of the Python extension - this PR modifies the python extension installation in vscode to manually install a version that works.
=> chore: fix up python extension installation for vscode

docker/py/entrypoint.sh
If a template adds a `post-init.sh` file, it cannot preserve the executable bit at the moment which causes the entrypoint to fail in running the extra script. This fixes the problem by running the script through `bash`. 
Thanks @ltalirz for pointing this out!
=> chore: use bash instead of executable scripts

docker/julia/Dockerfile, docker/vnc/Dockerfile
The latest version of the julia Dockerfiles is 1.5.3 but 1.6.1 is available now.
=> chore: update julia version to 1.6.1

docker/r/Dockerfile
Adds the possibility to launch the server through `start-notebook.sh`.
=> fix(r): add start-notebook.sh script

docker/r/Dockerfile
Upgrades RStudio to the newest working version, according to https://github.com/rocker-org/rocker-versioned2/issues/88#issuecomment-720013981
RStudio 1.4.X does not work yet, but #154 will be closed for now
closes #154
=> chore: upgrades rstudio to 1.3.959

.github/workflows/build_and_push_to_docker.yml, docker/r/Dockerfile
Adds R `4.0.5` ~~and `4.1.0` and bioconductor `3.13`~~ 
Bumping to R `4.1.0` and bioc `3.13` depends on #154 and #160.
=> chore: include newer R versions

scripts/install-vscode.sh
1. Update vscode version to the latest - 3.10.2
2. The issue with python extension is resolved in the latest version
3. Add pylint for python
=> chore: upgrade vscode and python extension

.github/workflows/build_and_push_to_docker.yml, README.md
With JupyterLab 3.0, the default Python version is now 3.9.
=> update python version 3.8 to 3.9

docker/batch/Dockerfile
gcc is necessary for most installations
=> chore: add gcc to base batch image

Makefile, docker/julia/post-init.sh, docker/py/entrypoint.sh, docker/py/git-config.bashrc, docker/r/post-init.sh, docker/vnc/post-init.sh
The goal of this is to maintain as much of the current behaviour with Amalthea-based sessions, while also keeping the images backwards compatible for now.
All the images which I've touched in this PR are on dockerhub as:
- ableuler/renkulab-py:b02a1a2
- ableuler/renkulab-r:b02a1a2-r4.0.4
- ableuler/renkulab-vnc:b02a1a2
- ableuler/renkulab-julia:b02a1a2
Projects on dev using these images are available under 
- https://dev.renku.ch/projects/andi/amalthea-python-image
- https://dev.renku.ch/projects/andi/amalthea-r-image
- https://dev.renku.ch/projects/andi/amalthea-vnc-image
- https://dev.renku.ch/projects/andi/amalthea-julia-image
as well as the respective path on the CI deployment which relies on Amalthea: https://ci-renku-2142.dev.renku.ch/
=> Adapt to Amalthea

docker/batch/Dockerfile, docker/py/Dockerfile, docker/py/requirements.txt
This PR is a reaction to a breaking change of setuptools which in turn broke our builds as pipx just pullst the latest of setuptools on a regular basis. We have therefore decided to remove pipx as it makes for non-reproducible builds.
=> fix: use virtualenv manually instead of pipx for renku install

docker/r/Dockerfile
This enables rstudio to open in an iframe. Tested here: https://ci-renku-2142.dev.renku.ch/projects/tasko.olevski/r-test-1 with the latest commit. Allows rstudio to work with the new UI and with Amalthea.
=> fix: allow rstudio to run in an iframe

docker/batch/Dockerfile, docker/py/Dockerfile, docker/py/requirements.txt
This bumps the notebooks base image from `lab-3.0.16` to `lab-3.2.1`, so a good look from the @SwissDataScienceCenter/poc squad to check if that breaks something would be appreciated.
=> Fix image build and bump base image version

docker/py/entrypoint.sh
#187 changed where `renku` is installed.
`renku` is now in either `$HOME/.renku/bin` or `/share/bin` (batch)
=> Fix renku not found error

docker/py/requirements.txt
=> chore: remove jupyterhub from base images

docker/py/Dockerfile, scripts/install-vscode.sh
Our change away from pipx had some unintended consequences on the `PATH` configuration and the existence of certain directories. This PR restores them back to a state that works with the vscode installation script.
=> chore: fix paths for vscode

.github/workflows/build_and_push_to_docker.yml
We should resolve the deeper issues surrounding RStudio and jupyter-rsession-proxy before trying to push more recent R-based images.
=> chore: do not build bioc-devel

scripts/install-vscode.sh
Bumps the default code-server version to `3.12.0`. Verified to work in commit `fb250e753` of https://renkulab.io/projects/rok.roskar/vscode-example
=> chore: bump default code-server version

.github/workflows/update-default-image-in-notebooks.yml
Example PR: https://github.com/SwissDataScienceCenter/renku-notebooks/pull/841
p.s. I added the quotation marks in the latest version of the workflow. So the image name is updated with the quotation marks.
closes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/792
=> chore(ci): update default image in notebooks on release

docker/r/Dockerfile
See here for a project that uses the images where the env variable has been added to R:
https://renkulab.io/projects/tasko.olevski/test-new-r-project-1
After this change the `RENKU_DISABLE_VERSION_CHECK=1` env variable shows up in the rstudio terminal.
The images built from this PR can be found in this workflow:
https://github.com/SwissDataScienceCenter/renkulab-docker/actions/runs/1554790636
=> fix: disable renku cli version check for R

.github/workflows/build_and_push_to_docker.yml, docker/julia/Dockerfile
Julia has recently been updated to 1.7.1. This PR upgrades it. See: https://julialang.org/downloads/#current_stable_release
=> chore: julia 1.6.1 -> 1.7.1

.github/workflows/build_and_push_to_docker.yml, docker/qgis/Dockerfile, docker/qgis/qgis.desktop
Due to demand from earth & environmental sciences, we have enabled QGIS to run as a GUI application on the Renku VNC.
=> feat: add qgis-enabled vnc renku image

docker/batch/Dockerfile, docker/py/Dockerfile
Bump the rp version again because 1.0.4 has some dependency resolution issues.
=> chore: bump rp because 1.0.4 is potentially buggy

.github/workflows/build_and_push_to_docker.yml, docker/r/Dockerfile
Fixes renku not being present in the PATH of rstudio images.
=> fix: add renku cli to PATH in rstudio

CHANGELOG.md
Most notably adds the renku cli in the path for R based images
=> chore: prep 0.11.1 release

.github/workflows/build_and_push_to_docker.yml, docker/r/Dockerfile
The reason for this is that the rocker/verse:devel image has switched to ubuntu 22.04 (jammy) but the rstudio .deb installer is only available for focal and older versions. The rstudio installation script builds the url from the ubuntu version and it just fails.
The rstudio version that is available for ubuntu 22.04 is `2022.02.3-492`. So I have switched the ci pipeline to use that for the devel image.
I will test if this work with renku.
=> fix: R image builds

.github/workflows/build_and_push_to_docker.yml
Updates the rstudio version for all images.
=> chore: bump rstudio version to 2022.02.3-492

docker/py/Dockerfile
The really old git lfs version is actually not working on the BIT deployment. But updating to a newer version works without a problem.
Even if this was not the case using a newer version of git LFS is a good idea.
=> chore: update git LFS to 3.2.0 for python images

.github/dependabot.yml
Let dependabot update the requirements.txt for the base python image
=> chore: enable dependabot updates on python libs

docker/cuda-tf/Dockerfile
The failing acceptance tests for `cuda-tf` image are caused because the jupyter server cannot start because of this:
```
Traceback (most recent call last):
File "/opt/conda/bin/jupyter-lab", line 6, in <module>
from jupyterlab.labapp import main
File "/opt/conda/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
from .labapp import LabApp
File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
from jupyterlab_server import slugify, WORKSPACE_EXTENSION
File "/opt/conda/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
from .app import LabServerApp
File "/opt/conda/lib/python3.8/site-packages/jupyterlab_server/app.py", line 7, in <module>
from jupyter_server.extension.application import ExtensionApp, …
```
=> fix: cuda-tf image builds

docker/qgis/Dockerfile
It seems that the gpg key was expired.
The qgis [docs](https://www.qgis.org/en/site/forusers/alldownloads.html#quickstart) show a new key that should be used.
=> fix: qgis image build

docker/py/requirements.txt
This was causing a lot of warnings in the console and making certain features of sessions buggy/unstable.
For example converting a notebook into anything would fail.
But also the notebooks and the jupyter server uses nbconver (for some reason) while it runs.
Example of failed client calls with our latest version:
Also failures such as this show up in the browser console:
With the update there are no such failed requests and the console has only warnings.
Here is a project that has the image from this PR pinned in its latest commit. In the first commit the older image that has issues is used.
There is an option to enable cypress to fail when there are any failures in the console. That would have caught this problem. I will enable it in a separate PR.
=> fix: broken nbconvert package

.github/dependabot.yml
It looks like the single dependabot spec pics up requirements files in all subdirectories.
=> chore: simplify dependabot config

.github/workflows/build_and_push_to_docker.yml
This has been tested with the current version of torch and it works on the limited cluster (built on VM, pushed to dockerhub and run on limited cluster).
=> chore(cuda): add build instructions for cuda 11.7

.github/workflows/build-and-push-to-docker.yml, Makefile, docker/py/Dockerfile, docker/qgis/Dockerfile, docker/vnc/Dockerfile
Replaces `conda install` with `mamba install` everywhere. 
closes #282
=> chore: use mamba everywhere

.github/workflows/build-and-push-to-docker.yml, Makefile, README.md, docker/cuda/Dockerfile, docker/julia/Dockerfile, docker/matlab/Dockerfile, docker/py/Dockerfile, docker/r/Dockerfile, docker/vnc/Dockerfile
Following the Makefile refactoring there were some issues with image tags - this PR sets up a consistent use of `DOCKER_LABEL` and other environment variables.
=> fix: image tagging consistency

docker/batch/Dockerfile, docker/generic/Dockerfile, docker/py/Dockerfile, docker/py/powerline.config, docker/r/Dockerfile
Adds rclone; also modifies the shell prompt to indicate whether you are running inside an ssh session:
The failing VNC build is fixed in #313
=> feat: add rclone and modify shell prompt

docker/py/entrypoint.sh
This PR injects a function into the entrypoint to override the jupyter command so that it can be forward compatible with newer images that no longer start the full server with `jupyter notebook`, making `/lab` yield a 404.
=> chore: override notebook command

docker/py/Dockerfile, docker/py/bashrc, docker/py/entrypoint.sh, docker/py/git-config.bashrc, docker/py/powerline.bashrc, docker/r/Dockerfile
`PATH` was set in some places via environment, which means it was not set on SSH. This PR fixes the problem. 
To reproduce the original issue, run a session with the `renku/renkulab-py:3.10-0.15.1` image and ssh into the session - it will fail because the `powerline-shell` is not found.
=> chore: ensure correct PATH on ssh

docker/py/bashrc
This ensures that the PATH is set correctly also in VSCode terminal sessions.
=> chore: make bashrc vscode compatible

.github/workflows/build-and-push-to-docker.yml
Encoding provenance metadata in images seems to cause problems for many common docker libraries. See [here](https://community.fly.io/t/images-built-with-the-latest-docker-buildx-and-or-github-actions-work-again/10816) for an explanation.
=> chore: do not add provenance metadata to images

docker/py/Dockerfile
Make sure the toil executables are in a directory that is on `PATH`
You can verify that this fixes the problem by [starting this session](https://renkulab.io/projects/rok.roskar/flights-tutorial-current/sessions/new?autostart=1), then doing `renku update --all`. It should update without errors.
=> chore: put toil execs on the path

.github/workflows/build-and-push-to-docker.yml
The notebook service cannot deal with images whose manifest is of type `application/vnd.oci.image.index.v1+json`. Basically any image with this type is considered to be missing. The type that works is `application/vnd.docker.distribution.manifest.v2+json`.
This change should force the R image to be of the type that works with the notebook service.
=> chore: force docker manifest for images

CHANGELOG.md
New release with the 11.8 cuda image
=> chore: prep release 0.19.0

.github/workflows/build-and-push-to-docker.yml, docker/r/Dockerfile
=> chore: add new R version

.github/workflows/build-and-push-to-docker.yml, docker/py/Dockerfile
Prior to this homedir python environment images were not tagged with latest or with the git tag.
=> chore(ci): publish tagged homedir env images

docker/py/renku-requirements/requirements.txt
Pinning this in the requirements here tends to not allow renku CLI to get updated. We don't really use it or need it in the base image, so it's better to remove the extra dependency anyway.
=> chore: remove sentry-sdk from the base image

.github/workflows/build-and-push-to-docker.yml, docker/py/Dockerfile
Adds python 3.11 to the matrix. Also builds a 3.11 VNC image
=> chore: add python 3.11 

.github/workflows/build-and-push-to-docker.yml, docker/r/Dockerfile, tests/cypress/e2e/jupyterlab.cy.ts, tests/cypress/e2e/rstudio.cy.ts, tests/index.ts, tests/package-lock.json, tests/package.json
=> chore: do not override RSTUDIO_VERSION in CI

.github/workflows/build-and-push-to-docker.yml, Makefile, docker/matlab-jupyter/Dockerfile
Adds a matlab image with [jupyter-matlab-proxy](https://github.com/mathworks/jupyter-matlab-proxy).
=> feat: add matlab-jupyter image

docker/py/Dockerfile
This helps to have nice defaults for all sessions.
=> fix: set workdir in jupyter sessions to $HOME
