docker/r/Dockerfile
Replaces the apt install with a conda RStudio install. 
closes #11 
cc @cchoirat
=> Update R dockerfile

.travis.yml, docker/base/Dockerfile
=> build: bump jh to 0.9.4 and add renku-python 0.5.0

Makefile, docker/base/Dockerfile
=> build: bump jh to 0.9.6

docker/base/Dockerfile
probably you might want to keep only `less` from this list - preferences?
=> add few packages that help in operations

.travis.yml
Build images with `renku-0.5.1`
=> build: add renku 0.5.1 to build matrix

docker/base/Dockerfile
* avoid the "rebuild lab" dialog on server launch
* update git-lfs to 2.8.0
=> avoid lab rebuild

docker/r/Dockerfile, docker/r/entrypoint.sh
For the R template, vim was missing, and there was no symlink to the project files from the RStudio interface. Both of these were added & tested here: https://renkulab.io/projects/1176/files
Fixes #56
=> added vim to Dockerfile and symlink for R in entrypoints

docker/r/Dockerfile
Hypothesizing why some of the matrix build is failing for these images.
=> pinned jupyterlab version and added pip timeout

.travis.yml, Makefile, docker/base/Dockerfile, docker/r/Dockerfile
latest version of pipx (15 from 14) has new syntax
=> updated syntax for pipx

.github/workflows/build_and_push_to_docker.yml, docker/bioc3_10/Dockerfile, docker/py3.7/requirements.txt, docker/r3.6.1/Dockerfile
* make sure that the renku version is pinned
* remove powerline from R images until we sort out the issue
=> image cleanup

docker/py3.7/Dockerfile
=> Install table-of-content jupyterlab extension

.github/workflows/build_and_push_to_docker.yml, README.md, docker/cuda10.0-tf1.14/Dockerfile, docker/cuda9.2/Dockerfile, docker/generic/Dockerfile, docker/julia1.3.1/Dockerfile, docker/r/Dockerfile
waiting for 0.10.4 release of renku-python for this to properly build.
=> chore: bump renku to 0.10.4

docker/py/entrypoint.sh, docker/r/entrypoint.sh
=> chore: install githooks via the entrypoint

docker/py/requirements.txt
update the dependencies of the base image.
=> chore: update base image dependencies

README.md
=> chore: remove pull reminders badge

docker/py/entrypoint.sh
Use the global git credentials for cloning the `renku-env` repo
=> fix: do the renku-env after git credentials are configured

.github/workflows/build_and_push_to_docker.yml, README.md, docker/julia/Dockerfile, docker/julia/post-init.sh
- Move Julia to version 1.5.3 (current stable)
- Update README
=> build: add Julia 1.5.3 (current stable) image

.github/workflows/build_and_push_to_docker.yml
- fixing Julia version bug in github actions workflow
=> chore: update julia workflow

docker/py/Dockerfile, docker/r/Dockerfile
=> feat: add jq to base py

.github/workflows/build_and_push_to_docker.yml, docker/batch/Dockerfile
=> feat: add base image for batch execution

docker/py/entrypoint.sh
Note: the race condition will be avoided by moving the cloning back to
an init container also with Amalthea.
=> fix: remove logic to avoid race condition in entrypoint

docker/batch/Dockerfile, docker/py/Dockerfile
version bump - normally this isn't necessary but since we're releasing a lot of things all at once might as well make it consistent.
=> chore: bump renku version

.github/workflows/build_and_push_to_docker.yml
Vnc-extensions build was duplicated in a merge. This PR de-duplicates it.
=> chore: de-duplicate vnc-extensions in build

CHANGELOG.md
This PR adds a changelog to version 0.11.0, which
- updates Renku versions
- adds MATLAB and QGIS images
- updates Julia image
- updates R and RStudio images
=> release: Update CHANGELOG.md

.github/workflows/build_and_push_to_docker.yml, docker/r/Dockerfile
NB: Devel is a 'relative' version - might cause confusion but hasn't come up yet.
=> Bumps R to 4.2.0

docker/cuda/Dockerfile
🤞 
Followed instructions from: https://forums.developer.nvidia.com/t/18-04-cuda-docker-image-is-broken/212892
closes #238
=> chore: fix cuda image builds

docker/batch/Dockerfile, docker/py/Dockerfile
Bump rp to latest published version.
=> chore: bump rp version to 1.4.0

CHANGELOG.md
=> chore: prepare 0.12.0 release

CHANGELOG.md
=> chore: prepare 0.13.0 release

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/github-project.yml
Adds issue templates and CI automation
=> chore: update issue templates and action for user issue triage

CHANGELOG.md
=> chore: prep release 0.15.0

CHANGELOG.md
=> chore: prep 0.15.0

.github/workflows/build-and-push-to-docker.yml
Adds bioconductor 3.16 to the build matrix.
=> feat: add bioc 3.16 and 3.17 to matrix

README.md
fixes the un-terminated code block
=> chore: fix readme formatting issue

CHANGELOG.md
=> chore: prep 0.17.0

CHANGELOG.md
=> chore: prep 0.18.0

.github/workflows/build-and-push-to-docker.yml, docker/cuda/Dockerfile
As requested by Firat.
There is also a package repo for this for 22.04 (which I added).
=> feat: add CUDA 11.8 images

.github/workflows/build-and-push-to-docker.yml, docker/py/Dockerfile
It is nice to be able to store the conda environments in the mounted folder in a session. This would allow people to not include their python packages in the image but install them once and then rely on the session pvcs to have them around after the session hibernates and restarts.
=> feat: image with conda packages in homedir

CHANGELOG.md
=> chore: prep 0.20.0 release

docker/py/Dockerfile
see https://github.com/jupyter/docker-stacks/issues/1990 for details
=> chore: remove unneded nodejs pin

docker/py/requirements.txt
The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-TORNADO-5840803
=> fix: docker/py/requirements.txt to reduce vulnerabilities (#379)

.github/workflows/build-and-push-to-docker.yml
adds latest bioconductor version
=> chore: add new bioc version

CHANGELOG.md
@rokroskar just a quick approve on the CHANGELOG.
=> chore: prep 0.21.1

.github/workflows/build-and-push-to-docker.yml
=> feat: add cuda 12.2

.github/workflows/build-and-push-to-docker.yml
=> chore: build multiarch vnc images

docker/matlab/Dockerfile
Use current version of matlab.
=> chore: update desktop matlab version

docker/matlab-jupyter/Dockerfile, docker/py/Dockerfile, docker/py/entrypoint.sh, docker/py/environment.yml
Continuation of #473. I just did not want to push directly to your branch @leafty.
=> feat: update images for new amalthea sessions

docker/py/Dockerfile, docker/py/environment.yml
This fixes #471 
Superseeds #475
=> chore: install backports.tarfile in base image 

.github/workflows/build-and-push-to-docker.yml
See: https://github.com/actions/runner-images/issues/11471#issuecomment-2663514074
=> fix: pin ubuntu + qemu for multi-arch builds

docker/vscodium-runimage/entrypoint.sh
Validated with image built with:
* `python+pip`
* `python+conda`
* `python+poetry v1`
=> feat: add virtualenv in vscodium runimage
